basePath: /
definitions:
  params.Item:
    properties:
      OrderID:
        type: integer
      description:
        type: string
      item_code:
        type: string
      quantity:
        type: integer
    type: object
  params.Order:
    properties:
      customer_name:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/params.Item'
        type: array
      ordered_at:
        type: string
    type: object
  params.OrderResponse:
    properties:
      additional_info:
        type: string
      message:
        type: string
      payload:
        $ref: '#/definitions/params.Order'
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: teguh@email.com
    name: Teguh Ainul Darajat
  description: Simple REST API developed developed for submission assigment 2 Bootcamp
    at Hacktive8
  title: Hacktiv8 Assigment 2
  version: "1.0"
paths:
  /orders:
    get:
      description: API for Get All order data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/params.OrderResponse'
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: API for create order
      parameters:
      - description: Create order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/params.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/params.OrderResponse'
      tags:
      - Orders
  /orders/:id:
    delete:
      description: API for Delete order data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/params.OrderResponse'
      tags:
      - Orders
    put:
      consumes:
      - application/json
      description: API for update order data
      parameters:
      - description: Update Order
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/params.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/params.OrderResponse'
      tags:
      - Orders
swagger: "2.0"
